<b> NUMPY <b>

In [93]:
# numpy a library for scientific caluclation
import numpy as np
# creating array
arr1 = np.array([1, 2, 3, 4])
print('NumPy Array: \n', arr1)
print('Dimension is: ', arr1.ndim)

NumPy Array: 
 [1 2 3 4]
Dimension is:  1


<b> BASIC OPERATIONS<b>

In [94]:
# adding two array
arr1 = np.array([2, 4, 6, 8])
arr2 = np.array([8, 6, 4, 2])
# gives sum of items of both arrar a1[0] + a2[0].....
print('Addition : \n', arr1 + arr2)

Addition : 
 [10 10 10 10]


In [95]:
# substracting two array
arr1 = np.array([2, 4, 6, 8])
arr2 = np.array([8, 6, 4, 2])
# gives difference of items of both arrar a1[0] - a2[0].....
print('Substraction : \n', arr2 - arr1)

Substraction : 
 [ 6  2 -2 -6]


In [96]:
# multiplication two array
arr1 = np.array([2, 4, 6, 8])
arr2 = np.array([8, 6, 4, 2])
# gives multiplication of items of both arrar a1[0] * a2[0].....
print('Multiplication : \n', arr2 * arr1)

Multiplication : 
 [16 24 24 16]


In [98]:
# division two array
arr1 = np.array([4, 3, 2, 1])
arr2 = np.array([8, 6, 4, 2])
# gives difference of items of both arrar a1[0] / a2[0].....
print('Division : \n', arr2 / arr1)

Division : 
 [2. 2. 2. 2.]


In [169]:
# standard deviation
arr1 = np.array([4, 3, 2, 1])
print('Standard Deviation : ', round(np.std(arr1), 2))

# mean 
print('Mean : ', round(np.mean(arr1), 2))

Standard Deviation :  1.12
Mean :  2.5


In [163]:
# dot product two array
arr1 = np.array([4, 3, 2, 1])
arr2 = np.array([8, 6, 4, 2])
# gives difference of items of both arrar a1[0] / a2[0].....
print('Dot Product : \n', arr2.dot(arr1))

# matrix product
print('Matrix Product : \n', arr1 @ arr2)

Dot Product : 
 60
Matrix Product : 
 60


<b> 2D ARRAY <b>

In [101]:
# 2 dimensional numpy array
twod_array = np.array([[2, 5], [4, 10], [6, 15], [8, 20]])
print('2D Array : \n', twod_array)

2D Array : 
 [[ 2  5]
 [ 4 10]
 [ 6 15]
 [ 8 20]]


In [102]:
# getting dimensions
print(twod_array.ndim, 'Dimension Array.')

2 Dimension Array.


In [103]:
# getting data type
print('Data Type is: ', twod_array.dtype)

Data Type is:  int32


In [104]:
# item size ( size of each item )
print('Item Size is: ', twod_array.itemsize)

Item Size is:  4


<b> COMPLEX ARRAY <b>

In [105]:
# complex type array
complex_twod_array = np.array([[2, 5], [4, 10], [6, 15], [8, 20]], dtype = complex)
print('Complex Array: \n', complex_twod_array)

Complex Array: 
 [[ 2.+0.j  5.+0.j]
 [ 4.+0.j 10.+0.j]
 [ 6.+0.j 15.+0.j]
 [ 8.+0.j 20.+0.j]]


<b> FLOAT ARRAY <b>

In [106]:
# float type array
float_twod_array = np.array([[2, 5], [4, 10], [6, 15], [8, 20]], dtype = float)
print('Float Array: \n', float_twod_array)

Float Array: 
 [[ 2.  5.]
 [ 4. 10.]
 [ 6. 15.]
 [ 8. 20.]]


In [107]:
# getting data type
print('Data Type is: ', float_twod_array.dtype)

Data Type is:  float64


In [108]:
# item size ( size of each item )
print('Item Size is: ', float_twod_array.itemsize)

Item Size is:  8


In [109]:
# shape of the array
print(twod_array.shape)
# return ( row, column )

(4, 2)


<b> ZEROS AND ONES ARRAY <b>

In [156]:
# zeros array with each value as 0.0 
zeros_array = np.zeros( (3, 4) )
print('Zeros Array: \n', zeros_array)

# ones array with each value as 1.0 
ones_array = np.ones( (3, 4) )
print('Ones Array: \n', ones_array)

# empty ndarray
empty_array = np.empty( (3,4) )
print('Empty Array: \n', empty_array)

Zeros Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Empty Array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


<b> ARRAY USING ARANGE <b>

In [111]:
range_arr = np.arange(1, 5)
print('Range Array: \n', range_arr)
# 2 step as 3rd param
step_arr = np.arange(1, 7, 2)
print('Step Array: \n', step_arr)

Range Array: 
 [1 2 3 4]
Step Array: 
 [1 3 5]


<b> LINSPACE ARRAY <b>

In [112]:
# array of linear sequence ( divides range in given parts )
lin_array = np.linspace(1, 5, 10)
print('Linspace Array: \n', lin_array)

Linspace Array: 
 [1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


<b> RESHAPE ARRAY <b>

In [113]:
# using reshape
print('Original Array: \n', twod_array)
print('Reshaped Array: \n', twod_array.reshape(2,4))

Original Array: 
 [[ 2  5]
 [ 4 10]
 [ 6 15]
 [ 8 20]]
Reshaped Array: 
 [[ 2  5  4 10]
 [ 6 15  8 20]]


In [171]:
# using ravel flatten the array in 1X1
print('Ravel Array: \n', twod_array.ravel())
print('Original Array: \n', twod_array)
# original array reamins unchanged

# transpose of ndarray
print('Transpose Array: \n', twod_array.T)
# original array reamins unchanged

# twod_array.resize ( changes the original one)

Ravel Array: 
 [ 2  5  4 10  6 15  8 20]
Original Array: 
 [[ 2  5]
 [ 4 10]
 [ 6 15]
 [ 8 20]]
Transpose Array: 
 [[ 2  4  6  8]
 [ 5 10 15 20]]


<b> MAX AND MIN ITEM OF ARRAY <b>

In [115]:
# minimum item in array
print('Original Array: \n', twod_array)
print('Minimum from Array: \n', twod_array.min())
# maximun item in array
print('Maximun from Array: \n', twod_array.max())

Original Array: 
 [[ 2  5]
 [ 4 10]
 [ 6 15]
 [ 8 20]]
Minimum from Array: 
 2
Maximun from Array: 
 20


<b> SUM OF ALL ITEMS IN ARRAY <b>

In [168]:
# sum of all the items in array
print('Original Array: \n', twod_array)
print('Sum of all items is : \n', twod_array.sum())

# cummulative sum 
cum_array = np.arange(12).reshape(3,4)
print('Original Array: \n', cum_array)
print('Cummulative Sum of all items is : \n', cum_array.cumsum(axis=1))


Original Array: 
 [[ 2  5]
 [ 4 10]
 [ 6 15]
 [ 8 20]]
Sum of all items is : 
 70
Original Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Cummulative Sum of all items is : 
 [[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [117]:
# sum of x axis items ( row wise )
print('Original Array: \n', twod_array)
print('Sum of all items X-axis : \n', twod_array.sum(axis=1))

Original Array: 
 [[ 2  5]
 [ 4 10]
 [ 6 15]
 [ 8 20]]
Sum of all items X-axis : 
 [ 7 14 21 28]


In [118]:
# sum of y axis items ( column wise )
print('Original Array: \n', twod_array)
print('Sum of all items Y-axis : \n', twod_array.sum(axis=0))

Original Array: 
 [[ 2  5]
 [ 4 10]
 [ 6 15]
 [ 8 20]]
Sum of all items Y-axis : 
 [20 50]


<B> SQUARE ROOT <B>
    

In [119]:
# sqaure root of array
new_array = np.array([[4, 16, 81], [9, 25, 49], [16, 36, 64]])
print('Array : \n', new_array)
print('Sqaured Root Array : \n', np.sqrt(new_array))

Array : 
 [[ 4 16 81]
 [ 9 25 49]
 [16 36 64]]
Sqaured Root Array : 
 [[2. 4. 9.]
 [3. 5. 7.]
 [4. 6. 8.]]


<b> INDEXING IN ARRAY <B>

In [123]:
# getting element by index 
array_2 = np.array([1, 2, 3, 4, 5])
print('Element at 1st index: ', array_2[1])
print('Element at 2nd index: ', array_2[2])

Element at 1st index:  2
Element at 2nd index:  3


In [135]:
# for 2D array
new_array = np.array([[4, 16, 81], [9, 25, 49], [16, 36, 64]])
print('Array : \n', new_array)
print(new_array[2,2])
# last element
print(new_array[-1])

Array : 
 [[ 4 16 81]
 [ 9 25 49]
 [16 36 64]]
64
[16 36 64]


<b> SLICING <b>

In [126]:
# getting value in some range
print(array_2[0:3])

[1 2 3]


In [127]:
# type
print(type(array_2[0:3]))

<class 'numpy.ndarray'>


In [136]:
# for 2D array
new_array = np.array([[4, 16, 81], [9, 25, 49], [16, 36, 64]])
print('Array : \n', new_array)
print(new_array[0:1, 1])
# last element
print(new_array[-1])

Array : 
 [[ 4 16 81]
 [ 9 25 49]
 [16 36 64]]
[16]
[16 36 64]


<B> ITERATING IN ARRAY <B>

In [137]:
# for loop iteration
for row in new_array:
    print(row)

[ 4 16 81]
[ 9 25 49]
[16 36 64]


In [139]:
# flating cell values using for loop
for cell in new_array.flat:
    print(cell)
# printing all element ( 1Xn matrix )

4
16
81
9
25
49
16
36
64


<B> STACKING OF ARRAY <B>

In [149]:
# stacking array one over other
array_11 = np.arange(6).reshape(3,2)
print('First Array: \n', array_11)
array_12 = np.arange(6, 12).reshape(3,2)
print('Second Array: \n', array_12)

# vertical stacking ( takes tuple as argument )
print('Vertical Stacking: \n', np.vstack( (array_11, array_12) ))

# horizontal stacking ( takes tuple as argument )
print('Horizontal Stacking: \n', np.hstack( (array_11, array_12) ))

First Array: 
 [[0 1]
 [2 3]
 [4 5]]
Second Array: 
 [[ 6  7]
 [ 8  9]
 [10 11]]
Vertical Stacking: 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
Horizontal Stacking: 
 [[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]
